config/routes.rb
Rails.application.routes.draw do
  get 'pages/example1'
  get 'pages/example2'
  get 'take_tests/check'
  post 'take_tests/check'

  resources :tests
  resources :answers
  resources :questions
  resources :tests
  resources :sections
  resources :take_tests

  devise_for :users

  resources :test do
  resources :response
end

devise_scope :user do
  authenticated :user do
    root 'sections#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/registrations#new', as: :unauthenticated_root
  end
end

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :tests
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_filter :landing_page
  before_action :authenticate_user!
  before_action :pass_test, only: [:show]
  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
    @user = current_user
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @sections = Section.find(params[:id])
    @all_sections = Section.all
  end

  # GET /sections/new
  def new
    @section = Section.new
    @test = Test.all
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:title, :body, :test_id)
    end

    def landing_page
       @disable_nav = true
    end
    
    def pass_test
      @user = current_user
      passed_tests = current_user.pssed_sections
      if passed_tests.include?(@section.test_id)
        true
      else
        redirect_to :controller => :take_tests, :action => :show
      end
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

   <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body%>
   </div>
  
  <div class="field">
   <% for test in @test.each %>
     <li><%= f.radio_button :test_id , "#{test.id}" %><%= h test.name %></li>
   <% end %>
  <div class="field">
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/_sidebar.html.erb
<!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Plagiarism Module
                    </a>
                </li>

                

                <li> <%= link_to "Example Test", pages_example1_path %>
            </ul>
        </div>
<!-- /#sidebar-wrapper -->

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<div id="wrapper">

  <%= render 'sections/sidebar' %>

  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          

           <h1> Welcome to the course <%= @user.first_name %> <%= @user.last_name %> </h1>


           <li><a href="/pages/example1"> Example Test</a></li>

          
          </div>
        </div>
    </div>

  </div>  <!-- /#page-content-wrapper -->   
     



</div> <!-- wrapper end !-->

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<div id="wrapper">

  <%= render 'sections/sidebar' %>


  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
        	<h1> Section <%= @section.title %> </h1>

          <br>

          <p> <%= @section.body %> </p>
		  <br>
		  <p> <%= @section.id %> </p>		  
          <br>
		 <%= link_to "Next Section", controller: "sections", action: "show", id: @section.id+1 %>

          <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
         </div>
        </div>
    </div>
  </div>  <!-- /#page-content-wrapper --> 




 </div>